version: '3.8'

services:
  mongo:
    image: mongo
    container_name: kuliah-mate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "4003:4003"
    depends_on:
      - mongo

  schedule-service:
    build: ./schedule-service
    container_name: schedule-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: kuliah-mate-frontend
    ports:
      - "5173:3000"
    depends_on:
      - schedule-service
      - task-service
      - auth-service
    volumes:
      - ./frontend/src:/app/src 

volumes:
  mongo-data: