version: '3.8'

services:
  mongo:
    image: mongo
    container_name: kuliah-mate-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  schedule-service:
    build: ./schedule-service
    container_name: schedule-service
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/schedule_db

  task-service:
    build: ./task-service
    container_name: task-service
    ports:
      - "4002:4002"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/task_db

  # SERVICE BARU: FRONTEND
  frontend:
    build: ./frontend
    container_name: kuliah-mate-frontend
    ports:
      - "3001:3000"
    depends_on:
      - schedule-service
      - task-service
    # Mapping volume agar bisa edit code live tanpa restart container (opsional)
    volumes:
      - ./frontend/src:/app/src 

volumes:
  mongo-data: